version: "3.9"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony-php
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:stable-alpine
        container_name: symfony-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:16.4
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: app_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    redis:
        image: redis:7.2
        container_name: redis-cache
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    db_data:
