version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        ports:
            - "8080:80"
        depends_on:
            - db
            - redis

    db:
        image: postgres:16.4
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: app_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    redis:
        image: redis:7.2
        container_name: redis-cache
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    db_data:
